version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  target-branch: dev
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: underscore
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
